<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

class MoroccanUsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $password = Hash::make('password123');

        $users = [
            // Admin (from demo specs to avoid credential breaking)
            [
                'name' => 'Admin Super',
                'email' => 'admin@bloodconnect.com',
                'password' => $password,
                'role' => 'admin',
                'phone' => '+212610203040',
                'city' => 'Oujda',
                'blood_type' => 'O+',
                'is_available' => true,
                'age' => 35,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
            ],

            // Organizers (for campaigns)
            [
                'name' => 'Association Al Amal Oujda',
                'email' => 'organizer@bloodconnect.com',
                'password' => $password,
                'role' => 'organizer',
                'phone' => '+212620304050',
                'city' => 'Oujda',
                'blood_type' => 'A+',
                'is_available' => false,
                'age' => 42,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar4.png',
            ],
            [
                'name' => 'Dr. Rachid Idrissi (Croissant Rouge)',
                'email' => 'dr.idrissi@bloodconnect.com',
                'password' => $password,
                'role' => 'organizer',
                'phone' => '+212630405060',
                'city' => 'Rabat',
                'blood_type' => 'O-',
                'is_available' => false,
                'age' => 48,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar5.png',
            ],

            // Donors
            [
                'name' => 'Karim El Amrani',
                'email' => 'karim.elamrani@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212661223344',
                'city' => 'Casablanca',
                'blood_type' => 'O+',
                'is_available' => true,
                'age' => 28,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
                'last_donation_at' => Carbon::now()->subMonths(4),
            ],
            [
                'name' => 'Fatima Zahra El Fassi',
                'email' => 'fatima.zahra@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212662445566',
                'city' => 'Rabat',
                'blood_type' => 'A+',
                'is_available' => true,
                'age' => 32,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar2.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Youssef Berrada',
                'email' => 'youssef.berrada@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212663778899',
                'city' => 'Marrakech',
                'blood_type' => 'B-',
                'is_available' => true,
                'age' => 45,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar6.png',
                'last_donation_at' => Carbon::now()->subMonths(6),
            ],
            [
                'name' => 'Amina Bennani',
                'email' => 'amina.bennani@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212664123123',
                'city' => 'Fes',
                'blood_type' => 'AB+',
                'is_available' => true,
                'age' => 24,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar7.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Hassan Alaoui',
                'email' => 'hassan.alaoui@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212665321321',
                'city' => 'Tangier',
                'blood_type' => 'O-',
                'is_available' => true,
                'age' => 38,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
                'last_donation_at' => Carbon::now()->subMonths(5),
            ],
            [
                'name' => 'Laila Benali',
                'email' => 'laila.benali@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212666123456',
                'city' => 'Oujda',
                'blood_type' => 'AB+',
                'is_available' => true,
                'age' => 29,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar2.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Tarik Mezouar',
                'email' => 'tarik.mezouar@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212667987654',
                'city' => 'Meknes',
                'blood_type' => 'B+',
                'is_available' => true,
                'age' => 34,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
                'last_donation_at' => Carbon::now()->subMonths(4),
            ],
            [
                'name' => 'Merieme Belkhayat',
                'email' => 'merieme.belkhayat@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212668554433',
                'city' => 'Fes',
                'blood_type' => 'A-',
                'is_available' => true,
                'age' => 27,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar6.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Zineb El Fassi',
                'email' => 'zineb.elfassi@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212669221100',
                'city' => 'Casablanca',
                'blood_type' => 'O+',
                'is_available' => true,
                'age' => 31,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar7.png',
                'last_donation_at' => Carbon::now()->subMonths(7),
            ],
            [
                'name' => 'Reda Berrada',
                'email' => 'reda.berrada@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212670776655',
                'city' => 'Marrakech',
                'blood_type' => 'B+',
                'is_available' => true,
                'age' => 40,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Yasmina Bennis',
                'email' => 'yasmina.bennis@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212671554499',
                'city' => 'Rabat',
                'blood_type' => 'A+',
                'is_available' => true,
                'age' => 26,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar2.png',
                'last_donation_at' => Carbon::now()->subMonths(10),
            ],
            [
                'name' => 'Khalid Tazi',
                'email' => 'khalid.tazi@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212672112233',
                'city' => 'Kenitra',
                'blood_type' => 'O-',
                'is_available' => true,
                'age' => 43,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Asmae El Idrissi',
                'email' => 'asmae.idrissi@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212673443322',
                'city' => 'Agadir',
                'blood_type' => 'AB+',
                'is_available' => true,
                'age' => 29,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar6.png',
                'last_donation_at' => Carbon::now()->subMonths(4),
            ],
            [
                'name' => 'Anas Filali',
                'email' => 'anas.filali@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212674998877',
                'city' => 'El Jadida',
                'blood_type' => 'B-',
                'is_available' => true,
                'age' => 36,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Bouchra Skali',
                'email' => 'bouchra.skali@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212675665544',
                'city' => 'Tetouan',
                'blood_type' => 'AB-',
                'is_available' => true,
                'age' => 41,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar2.png',
                'last_donation_at' => Carbon::now()->subMonths(8),
            ],
            [
                'name' => 'Mustapha Alami',
                'email' => 'mustapha.alami@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212676112233',
                'city' => 'Safi',
                'blood_type' => 'O+',
                'is_available' => true,
                'age' => 50,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Hanane Chraibi',
                'email' => 'hanane.chraibi@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212677889900',
                'city' => 'Meknes',
                'blood_type' => 'A+',
                'is_available' => true,
                'age' => 33,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar6.png',
                'last_donation_at' => Carbon::now()->subMonths(5),
            ],
            [
                'name' => 'Othmane Bennani',
                'email' => 'othmane.bennani@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212678123456',
                'city' => 'Casablanca',
                'blood_type' => 'B+',
                'is_available' => true,
                'age' => 27,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
                'last_donation_at' => null,
            ],
            [
                'name' => 'Nabil Chraibi Senior',
                'email' => 'nabil.senior@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212679987654',
                'city' => 'Rabat',
                'blood_type' => 'AB+',
                'is_available' => true,
                'age' => 52,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
                'last_donation_at' => Carbon::now()->subMonths(11),
            ],
            [
                'name' => 'Meryem Alaoui',
                'email' => 'meryem.alaoui@example.com',
                'password' => $password,
                'role' => 'donor',
                'phone' => '+212680123456',
                'city' => 'Tangier',
                'blood_type' => 'O-',
                'is_available' => true,
                'age' => 30,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar7.png',
                'last_donation_at' => null,
            ],

            // Patients (Recipients)
            [
                'name' => 'Khadija Tazi',
                'email' => 'khadija.tazi@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212611223344',
                'city' => 'Casablanca',
                'blood_type' => 'A-',
                'is_available' => false,
                'age' => 50,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar2.png',
            ],
            [
                'name' => 'Nabil Chraibi',
                'email' => 'nabil.chraibi@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212611556677',
                'city' => 'Agadir',
                'blood_type' => 'O+',
                'is_available' => false,
                'age' => 42,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
            ],
            [
                'name' => 'Salma Lahlou',
                'email' => 'salma.lahlou@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212611889900',
                'city' => 'Rabat',
                'blood_type' => 'B+',
                'is_available' => false,
                'age' => 19,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar6.png',
            ],
            [
                'name' => 'Omar Mansouri',
                'email' => 'omar.mansouri@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212622334455',
                'city' => 'Marrakech',
                'blood_type' => 'AB-',
                'is_available' => false,
                'age' => 60,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
            ],
            [
                'name' => 'Rachid Idrissi',
                'email' => 'rachid.idrissi@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212622667788',
                'city' => 'Fes',
                'blood_type' => 'A+',
                'is_available' => false,
                'age' => 27,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar3.png',
            ],
            [
                'name' => 'Houda Tazi',
                'email' => 'houda.tazi@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212622998877',
                'city' => 'Oujda',
                'blood_type' => 'O-',
                'is_available' => false,
                'age' => 31,
                'gender' => 'Female',
                'profile_photo_path' => 'defaults/avatars/avatar2.png',
            ],
            [
                'name' => 'Hamza Belghiti',
                'email' => 'hamza.belghiti@example.com',
                'password' => $password,
                'role' => 'patient',
                'phone' => '+212623112233',
                'city' => 'Casablanca',
                'blood_type' => 'AB+',
                'is_available' => false,
                'age' => 68,
                'gender' => 'Male',
                'profile_photo_path' => 'defaults/avatars/avatar1.png',
            ]
        ];

        foreach ($users as $user) {
            User::updateOrCreate(
                ['email' => $user['email']],
                $user
            );
        }
    }
}
